### ISSUE TITLE
Connecting the sensors and all other...

### ISSUE THREAD

**Issue by prassaschr** [heythisisnate/nodemcu-smartthings-sensors#7]
Hi.
Kindly asking for the details below: 
1. A connection schema (connection diagram) with the sensors and power and all other required parts.
2. The power voltage is 3,3V or 5V?

Thank you

**Comment by prassaschr** [comment]
I think that the sensors (PIR) work with 12V and have 6 cables (2 for 12V power, 2 for movement sensor and 2 for tamper) and the door contacts work also with 12 V (directly from the main board).

How can I connect them to the board? Voltage etc?

Thank you in advance!

**Comment by heythisisnate** [comment]
Hi @prassaschr, sorry for the slow reply. I didn't see this!

I don't have a schema, but the wiring is very simple. For contact sensors, these are very simple and only have two wires. They don't need a separate power. Simply connect one wire to the GND and one wire to the pin D2 (for example).

Motion sensors usually have four wires. The black/red wires are for the 12V power, leave that connected to the power output on your alarm panel. The other pair is the signal wire. Just connect those the same way as contact sensors.

The ESP8266 outputs 3.3V, but in this case the output doesn't matter because it's not powering anything.
